config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "chat_rooms#index"
  resources :chat_rooms, only: [:new, :create, :show, :index]
  mount ActionCable.server => '/cable'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 1, maximum: 1000}
  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :chat_rooms, dependent: :destroy
         has_many :messages, dependent: :destroy
         attr_accessor :login
         validates :username, :presence => true, :uniqueness => { :case_sensitive => false }
         validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  def name
    username.capitalize
  end

  def self.find_for_database_authentication warden_conditions
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.strip.downcase}]).first
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
    @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
    @message = Message.new
  end

   private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end
end

#add useful links to index, move to left add banners for the links on right
#add list of chat rooms add to seed, and delete add room button
#host to heroku

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat_rooms/_chat_room.html.erb
<br>
<%= link_to "Talk about #{chat_room.title}", chat_room_path(chat_room) %><br><br>

app/views/chat_rooms/index.html.erb
<h1>Mens Mental Health Chatrooms</h1>

<p class="lead"><%= link_to 'Add new chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<br>
<br>
<br>
<ul>
  <div id="chat-rooms"
  <%= render @chat_rooms %>
</div>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<h2>Talk About <%= @chat_room.title %></h2>

<div id="wrapper">
  <div id="menu">
    <p class="welcome">Welcome, <%= current_user.username %> <b></b></p>
    <p class="logout"><a id="exit" <%= link_to 'Exit Room', chat_rooms_path %></p>
      <div style="clear:both"></div>
    </div>


<div id="messages" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
</div>
  <div>
     <%= form_for @message, url: '#' do |f| %>
       <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
       <div class="form-group">
         <%= f.text_area :body, class: 'form-control' %>
         <%= f.submit "Post", class: 'submit' %>
       </div>
     <% end %>
</div>
</div>
<br>
<br>
<a href="http://www.mind.org.uk/">mind.org.uk</a><br>
<a href="https://www.thecalmzone.net/">thecalmzone.net</a><br>
<a href="https://www.menshealthforum.org.uk/">menshealthforum</a><br>
<a href="http://www.nhs.uk/Conditions/stress-anxiety-depression/Pages/low-mood-stress-anxiety.aspx">nhsadvice</a><br>
<a href="http://www.youngminds.org.uk/"> mentalhealthforyoungpeople</a><br>
<a href="https://turn2me.org/">freecounselling</a><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MenTalkAboutMentalHealth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <div id="sign_out">
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
    <% end %>
  </div>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-11">
        <p class="card-text">
            <% if message.user.name.first > 'M' %>
            <span class="pink-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
            <% else %>
            <span class="text-muted"><%= message.user.name %> at <%= message.timestamp %> says</span><br>
            <% end %>
            <%= message.body %>
        </p>
      </div>
    </div>
  </div>
</div>